// This file is generated by the builder script. Do not edit.
// To rebuild, click Settings > Tools > Build in the app or run 'npm run build-unidata' in the wwwassets folder
export type UnicodeEmojiGroup = 
	{group: "Smileys & Emotion", subGroup: "face-smiling"}
	| {group: "Smileys & Emotion", subGroup: "face-affection"}
	| {group: "Smileys & Emotion", subGroup: "face-tongue"}
	| {group: "Smileys & Emotion", subGroup: "face-hand"}
	| {group: "Smileys & Emotion", subGroup: "face-neutral-skeptical"}
	| {group: "Smileys & Emotion", subGroup: "face-sleepy"}
	| {group: "Smileys & Emotion", subGroup: "face-unwell"}
	| {group: "Smileys & Emotion", subGroup: "face-hat"}
	| {group: "Smileys & Emotion", subGroup: "face-glasses"}
	| {group: "Smileys & Emotion", subGroup: "face-concerned"}
	| {group: "Smileys & Emotion", subGroup: "face-negative"}
	| {group: "Smileys & Emotion", subGroup: "face-costume"}
	| {group: "Smileys & Emotion", subGroup: "cat-face"}
	| {group: "Smileys & Emotion", subGroup: "monkey-face"}
	| {group: "Smileys & Emotion", subGroup: "heart"}
	| {group: "Smileys & Emotion", subGroup: "emotion"}
	| {group: "People & Body", subGroup: "hand-fingers-open"}
	| {group: "People & Body", subGroup: "hand-fingers-partial"}
	| {group: "People & Body", subGroup: "hand-single-finger"}
	| {group: "People & Body", subGroup: "hand-fingers-closed"}
	| {group: "People & Body", subGroup: "hands"}
	| {group: "People & Body", subGroup: "hand-prop"}
	| {group: "People & Body", subGroup: "body-parts"}
	| {group: "People & Body", subGroup: "person"}
	| {group: "People & Body", subGroup: "person-gesture"}
	| {group: "People & Body", subGroup: "person-role"}
	| {group: "People & Body", subGroup: "person-fantasy"}
	| {group: "People & Body", subGroup: "person-activity"}
	| {group: "People & Body", subGroup: "person-sport"}
	| {group: "People & Body", subGroup: "person-resting"}
	| {group: "People & Body", subGroup: "family"}
	| {group: "People & Body", subGroup: "person-symbol"}
	| {group: "Component", subGroup: "skin-tone"}
	| {group: "Component", subGroup: "hair-style"}
	| {group: "Animals & Nature", subGroup: "animal-mammal"}
	| {group: "Animals & Nature", subGroup: "animal-bird"}
	| {group: "Animals & Nature", subGroup: "animal-amphibian"}
	| {group: "Animals & Nature", subGroup: "animal-reptile"}
	| {group: "Animals & Nature", subGroup: "animal-marine"}
	| {group: "Animals & Nature", subGroup: "animal-bug"}
	| {group: "Animals & Nature", subGroup: "plant-flower"}
	| {group: "Animals & Nature", subGroup: "plant-other"}
	| {group: "Food & Drink", subGroup: "food-fruit"}
	| {group: "Food & Drink", subGroup: "food-vegetable"}
	| {group: "Food & Drink", subGroup: "food-prepared"}
	| {group: "Food & Drink", subGroup: "food-asian"}
	| {group: "Food & Drink", subGroup: "food-sweet"}
	| {group: "Food & Drink", subGroup: "drink"}
	| {group: "Food & Drink", subGroup: "dishware"}
	| {group: "Travel & Places", subGroup: "place-map"}
	| {group: "Travel & Places", subGroup: "place-geographic"}
	| {group: "Travel & Places", subGroup: "place-building"}
	| {group: "Travel & Places", subGroup: "place-religious"}
	| {group: "Travel & Places", subGroup: "place-other"}
	| {group: "Travel & Places", subGroup: "transport-ground"}
	| {group: "Travel & Places", subGroup: "transport-water"}
	| {group: "Travel & Places", subGroup: "transport-air"}
	| {group: "Travel & Places", subGroup: "hotel"}
	| {group: "Travel & Places", subGroup: "time"}
	| {group: "Travel & Places", subGroup: "sky & weather"}
	| {group: "Activities", subGroup: "event"}
	| {group: "Activities", subGroup: "award-medal"}
	| {group: "Activities", subGroup: "sport"}
	| {group: "Activities", subGroup: "game"}
	| {group: "Activities", subGroup: "arts & crafts"}
	| {group: "Objects", subGroup: "clothing"}
	| {group: "Objects", subGroup: "sound"}
	| {group: "Objects", subGroup: "music"}
	| {group: "Objects", subGroup: "musical-instrument"}
	| {group: "Objects", subGroup: "phone"}
	| {group: "Objects", subGroup: "computer"}
	| {group: "Objects", subGroup: "light & video"}
	| {group: "Objects", subGroup: "book-paper"}
	| {group: "Objects", subGroup: "money"}
	| {group: "Objects", subGroup: "mail"}
	| {group: "Objects", subGroup: "writing"}
	| {group: "Objects", subGroup: "office"}
	| {group: "Objects", subGroup: "lock"}
	| {group: "Objects", subGroup: "tool"}
	| {group: "Objects", subGroup: "science"}
	| {group: "Objects", subGroup: "medical"}
	| {group: "Objects", subGroup: "household"}
	| {group: "Objects", subGroup: "other-object"}
	| {group: "Symbols", subGroup: "transport-sign"}
	| {group: "Symbols", subGroup: "warning"}
	| {group: "Symbols", subGroup: "arrow"}
	| {group: "Symbols", subGroup: "religion"}
	| {group: "Symbols", subGroup: "zodiac"}
	| {group: "Symbols", subGroup: "av-symbol"}
	| {group: "Symbols", subGroup: "gender"}
	| {group: "Symbols", subGroup: "math"}
	| {group: "Symbols", subGroup: "punctuation"}
	| {group: "Symbols", subGroup: "currency"}
	| {group: "Symbols", subGroup: "other-symbol"}
	| {group: "Symbols", subGroup: "keycap"}
	| {group: "Symbols", subGroup: "alphanum"}
	| {group: "Symbols", subGroup: "geometric"}
	| {group: "Flags", subGroup: "flag"}
	| {group: "Flags", subGroup: "country-flag"}
	| {group: "Flags", subGroup: "subdivision-flag"};
