// noinspection SpellCheckingInspection

export const EXTEND_ALIASES: Record<string, string[]> = {
	"·": ["\\cdotp", "\\centerdot"],
	"•": ["\\smblkcircle", "\\bullet"],
	"√": ["\\sqrt", "\\surd"],
	"∛": ["\\cuberoot"],
	"∜": ["\\fourthroot"],
	"‖": ["\\Vert"],
	"⦀": ["\\Vvert"],
	"⌈": ["\\lceil"],
	"⌜": ["\\ulcorner", "upper left corner"],
	"⌉": ["\\rceil"],
	"⌝": ["\\urcorner", "upper right corner"],
	"⌊": ["\\lfloor"],
	"⌞": ["\\llcorner", "lower left corner"],
	"⌋": ["\\rfloor"],
	"⌟": ["\\lrcorner", "lower right corner"],
	"⎰": ["\\lmoustache", "upper left or lower right curly bracket section"],
	"⎱": ["\\rmoustache", "upper right or lower left curly bracket section"],
	"⟅": ["\\lbag"],
	"⟆": ["\\rbag"],
	"⟨": ["\\langle"],
	"⦑": ["\\langledot"],
	"⟩": ["\\rangle"],
	"⦒": ["\\rangledot"],
	"⧼": ["\\lcurvyangle"],
	"⧽": ["\\rcurvyangle"],
	"⟪": ["\\lAngle"],
	"⟫": ["\\rAngle"],
	"⟮": ["\\lgroup"],
	"⟯": ["\\rgroup"],
	"❲": ["\\lbrbrak"],
	"⦘": ["\\rblkbrbrak"],
	"⦗": ["\\lblkbrbrak"],
	"❳": ["\\rbrbrak"],
	"⦋": ["\\lbrackubar"],
	"⦌": ["\\rbrackubar"],
	"⦍": ["\\lbrackultick"],
	"⦎": ["\\rbracklrtick"],
	"⦏": ["\\lbracklltick"],
	"⦐": ["\\rbrackurtick"],
	"⦓": ["\\lparenless"],
	"⦕": ["\\Lparengtr"],
	"⦔": ["\\rparengtr"],
	"⦖": ["\\Rparenless"],
	"⦅": ["\\lParen"],
	"⦇": ["\\llparenthesis"],
	"⦆": ["\\rParen"],
	"⦈": ["\\rrparenthesis"],
	"⟦": ["\\lBrack"],
	"⟬": ["\\Lbrbrak"],
	"⟧": ["\\rBrack"],
	"⟭": ["\\Rbrbrak"],
	"⦃": ["\\lBrace"],
	"⦄": ["\\rBrace"],
	"⦉": ["\\llangle"],
	"⦊": ["\\rrangle"],
	"⧘": ["\\lvzigzag"],
	"⧚": ["\\Lvzigzag"],
	"⧙": ["\\rvzigzag"],
	"⧛": ["\\Rvzigzag"],
	"⟌": ["\\longdivision"],
	"̀": ["\\grave"],
	"́": ["\\acute"],
	"̂": ["\\hat"],
	"̃": ["\\tilde"],
	"̅": ["\\overbar"],
	"̄": ["\\bar"],
	"̿": ["\\Bar"],
	"̌": ["\\check"],
	"̆": ["\\breve"],
	"̐": ["\\candra"],
	"̒": ["\\oturnedcomma"],
	"̕": ["\\ocommatopright"],
	"̚": ["\\droang"],
	"̇": ["\\dot"],
	"̈": ["\\ddot"],
	"⃛": ["\\dddot"],
	"⃨": ["\\threeunderdot"],
	"⃜": ["\\ddddot"],
	"̉": ["\\ovhook"],
	"̊": ["\\ocirc"],
	"⃗": ["\\vec"],
	"⃐": ["\\leftharpoonaccent"],
	"⃑": ["\\hvec"],
	"⃡": ["\\tvec"],
	"⃒": ["\\vertoverlay"],
	"⃧": ["\\annuity"],
	"⃩": ["\\widebridgeabove"],
	"⃰": ["\\asteraccent"],
	"′": ["\\prime"],
	"″": ["\\dprime"],
	"‴": ["\\trprime"],
	"⁗": ["\\qprime"],
	"‵": ["\\backprime"],
	"‶": ["\\backdprime"],
	"‷": ["\\backtrprime"],
	"⏞": ["\\overbrace"],
	"⏟": ["\\underbrace"],
	"⎴": ["\\overbracket"],
	"⎵": ["\\underbracket"],
	"⏜": ["\\overparen"],
	"⏝": ["\\underparen"],
	"⏠": ["\\overshell", "\\obrbrak"],
	"⏡": ["\\undershell", "\\ubrbrak"],
	"∑": ["\\sum"],
	"⅀": ["\\Bbbsum"],
	"⨊": ["\\modtwosum"],
	"∫": ["\\int"],
	"∬": ["\\iint"],
	"∭": ["\\iiint"],
	"⨌": ["\\iiiint"],
	"∮": ["\\oint"],
	"∯": ["\\oiint"],
	"∰": ["\\oiiint"],
	"∱": ["\\intclockwise"],
	"∲": ["\\coint", "\\varointclockwise"],
	"∳": ["\\aoint", "\\ointctrclockwise"],
	"⨍": ["\\intbar"],
	"⨎": ["\\intBar"],
	"⨏": ["\\fint"],
	"⨐": ["\\cirfnint"],
	"⨑": ["\\awint"],
	"⨒": ["\\rppolint"],
	"⨓": ["\\scpolint"],
	"⨔": ["\\npolint"],
	"⨕": ["\\pointint"],
	"⨖": ["\\sqint"],
	"⨗": ["\\intlarhk"],
	"⨘": ["\\intx"],
	"⨙": ["\\intcap"],
	"⨚": ["\\intcup"],
	"⨛": ["\\upint"],
	"⨜": ["\\lowint"],
	"⨋": ["\\sumint"],
	"∏": ["\\prod"],
	"∐": ["\\amalg", "\\coprod"],
	"⋀": ["\\bigwedge"],
	"⨇": ["\\conjquant"],
	"⋁": ["\\bigvee"],
	"⨈": ["\\disjquant"],
	"⋂": ["\\bigcap"],
	"⋃": ["\\bigcup"],
	"⨃": ["\\bigcupdot"],
	"⨄": ["\\biguplus"],
	"⨅": ["\\bigsqcap"],
	"⨆": ["\\bigsqcup"],
	"⨝": ["\\Join join⊍"],
	"⟗": ["\\fullouterjoin"],
	"⟕": ["\\leftouterjoin"],
	"⟖": ["\\rightouterjoin"],
	"⨞": ["\\bigtriangleleft"],
	"⧸": ["\\xsol"],
	"⧹": ["\\xbsol"],
	"⨀": ["\\bigodot"],
	"⨁": ["\\bigoplus"],
	"⨂": ["\\bigotimes"],
	"⨉": ["\\bigtimes"],
	"⨟": ["\\zcmp"],
	"⨠": ["\\zpipe"],
	"⨡": ["\\zproject"],
	"⫼": ["\\biginterleave"],
	"⫿": ["\\bigtalloblong"],
	"𞻰": ["\\arabicmaj"],
	"𞻱": ["\\arabichad"],
	"⊕": ["\\oplus"],
	"⨭": ["\\opluslhrim"],
	"⨮": ["\\oplusrhrim"],
	"⊖": ["\\ominus"],
	"⊙": ["\\odot"],
	"⊗": ["\\otimes"],
	"⨶": ["\\otimeshat"],
	"⨴": ["\\otimeslhrim"],
	"⨵": ["\\otimesrhrim"],
	"⨷": ["\\Otimes"],
	"⨸": ["\\odiv"],
	"⊘": ["\\oslash"],
	"⊛": ["\\circledast"],
	"⊚": ["\\circledcirc"],
	"⊜": ["\\circledequal"],
	"⊝": ["\\circleddash"],
	"⦵": ["\\circlehbar"],
	"⌽": ["\\obar"],
	"⦶": ["\\circledvert"],
	"⦷": ["\\circledparallel"],
	"⦸": ["\\obslash"],
	"⦹": ["\\operp"],
	"⧀": ["\\olessthan"],
	"⧁": ["\\ogreaterthan"],
	"⦻": ["\\olcross"],
	"⦼": ["\\odotslashdot"],
	"⦽": ["\\uparrowoncircle"],
	"⦾": ["\\circledwhitebullet"],
	"⦿": ["\\circledbullet"],
	"⊞": ["\\boxplus"],
	"⊟": ["\\boxminus"],
	"⊡": ["\\boxdot", "\\dotsquare"],
	"⊠": ["\\boxtimes"],
	"⧄": ["\\boxdiag"],
	"⧆": ["\\boxast"],
	"⧇": ["\\boxcircle"],
	"⨹": ["\\triangleplus"],
	"⨺": ["\\triangleminus"],
	"◬": ["\\trianglecdot"],
	"⨻": ["\\triangletimes"],
	"⩲": ["\\pluseqq"],
	"⩱": ["\\eqqplus"],
	"∔": ["\\dotplus"],
	"⨢": ["\\ringplus"],
	"⨣": ["\\plushat"],
	"⨤": ["\\simplus"],
	"⨥": ["\\plusdot"],
	"⨦": ["\\plussim"],
	"⨧": ["\\plussubtwo"],
	"⨨": ["\\plustrif"],
	"⧺": ["\\doubleplus"],
	"⧻": ["\\tripleplus"],
	"∸": ["\\dotminus"],
	"⨩": ["\\commaminus"],
	"⨪": ["\\minusdot"],
	"⨫": ["\\minusfdots"],
	"⨬": ["\\minusrdots"],
	"⧾": ["\\tplus"],
	"⧿": ["\\tminus"],
	"⋉": ["\\ltimes"],
	"⋊": ["\\rtimes"],
	"⋋": ["\\leftthreetimes"],
	"⋌": ["\\rightthreetimes"],
	"⨰": ["\\dottimes"],
	"⨱": ["\\timesbar"],
	"⨲": ["\\btimes"],
	"⨳": ["\\smashtimes"],
	"⋇": ["\\divideontimes"],
	"⫽": ["\\sslash"],
	"⫻": ["\\trslash"],
	"⧶": ["\\dsol"],
	"⟑": ["\\wedgedot", "logical and with dot"],
	"⋏": ["\\curlywedge"],
	"⌅": ["\\varbarwedge", "\\barwedge", "logical and with bar above"],
	"⌆": ["\\vardoublebarwedge", "\\doublebarwedge", "logical and with double bar above"],
	"⩑": ["\\wedgeodot"],
	"⩚": ["\\wedgemidvert"],
	"⩜": ["\\midbarwedge"],
	"⩞": ["\\doublebarwedge"],
	"⩟": ["\\wedgebar"],
	"⩠": ["\\wedgedoublebar"],
	"⩘": ["\\bigslopedwedge"],
	"⩓": ["\\Wedge"],
	"⩕": ["\\wedgeonwedge"],
	"⊻": ["\\veebar", "logical or with bar below", "exclusive disjunction"],
	"⟇": ["\\veedot", "logical or with dot inside"],
	"⋎": ["\\curlyvee", "curly logical or"],
	"⩒": ["\\veeodot"],
	"⩛": ["\\veemidvert"],
	"⩝": ["\\midbarvee"],
	"⩡": ["\\varveebar"],
	"⩢": ["\\doublebarvee"],
	"⩣": ["\\veedoublebar"],
	"⩗": ["\\bigslopedvee"],
	"⩔": ["\\Vee"],
	"⩖": ["\\veeonvee"],
	"⩀": ["\\capdot"],
	"⩃": ["\\barcap"],
	"⩄": ["\\capwedge"],
	"⩋": ["\\twocaps"],
	"⩍": ["\\closedvarcap"],
	"⋒": ["\\Cap", "\\doublecap"],
	"⊌": ["\\cupleftarrow"],
	"⩁": ["\\uminus"],
	"⩂": ["\\barcup"],
	"⩅": ["\\cupvee"],
	"⩊": ["\\twocups"],
	"⩌": ["\\closedvarcup"],
	"⩐": ["\\closedvarcupsmashprod"],
	"⋓": ["\\Cup", "\\doublecup"],
	"⩆": ["\\cupovercap"],
	"⩈": ["\\cupbarcap"],
	"⩇": ["\\capovercup"],
	"⩉": ["\\capbarcup"],
	"±": ["\\pm", "plus-or-minus"],
	"∓": ["\\mp", "minus-plus"],
	"+": ["\\mathplus"],
	"−": ["\\minus"],
	"⋅": ["\\cdot", "small middle dot"],
	"⋆": ["\\star", "small star, filled, low"],
	"∙": ["\\vysmblkcircle", "bullet operator"],
	"×": ["\\times", "multiply sign"],
	"⨯": ["\\vectimes"],
	"÷": ["\\div", "divide sign"],
	"∕": ["\\divslash"],
	"⁄": ["\\fracslash"],
	"⧵": ["\\setminus"],
	"⧷": ["\\rsolbar"],
	"∖": ["\\smallsetminus", "small set minus"],
	"∗": ["\\ast", "centered asterisk"],
	"∘": ["\\vysmwhtcircle", "composite function", "small circle"],
	"∧": ["\\wedge", "\\land"],
	"⊼": ["\\barwedge", "bar, wedge", "logical and with bar above"],
	"∨": ["\\vee", "\\lor"],
	"⊽": ["\\barvee", "bar, vee", "logical or with bar above"],
	"∩": ["\\cap"],
	"∪": ["\\cup", "logical sum"],
	"⊍": ["\\cupdot", "union with dot"],
	"⊎": ["\\uplus"],
	"⊓": ["\\sqcap", "square intersection"],
	"⩎": ["\\Sqcap"],
	"⊔": ["\\sqcup", "square union"],
	"⩏": ["\\Sqcup"],
	"†": ["\\dagger"],
	"‡": ["\\ddagger"],
	"⁀": ["\\tieconcat"],
	"∾": ["\\invlazys"],
	"≀": ["\\wr"],
	"⅋": ["\\upand"],
	"⊺": ["\\intercal"],
	"⧖": ["\\hourglass"],
	"⧗": ["\\blackhourglass"],
	"⧢": ["\\shuffle"],
	"⨾": ["\\fcmp"],
	"⨿": ["\\amalg"],
	"⫴": ["\\interleave"],
	"⫵": ["\\nhVvert"],
	"⫶": ["\\threedotcolon"],
	"⫾": ["\\talloblong"],
	"⨼": ["\\intprod"],
	"⨽": ["\\intprodr"],
	"§": ["\\mathsection"],
	"¬": ["\\neg", "\\lnot"],
	"⌐": ["\\invnot"],
	"¶": ["\\mathparagraph"],
	"Ƶ": ["\\Zbar", "impedance"],
	"϶": ["\\upbackepsilon"],
	"―": ["\\horizbar"],
	"‗": ["\\twolowline"],
	"‥": ["\\enleadertwodots", "double baseline dot", "en leader"],
	"…": ["\\unicodeellipsis"],
	"‸": ["\\caretinsert", "insertion mark"],
	"‼": ["\\Exclam"],
	"⁃": ["\\hyphenbullet", "filled rectangle"],
	"⁇": ["\\Question"],
	"ℇ": ["\\Eulerconst"],
	"ℎ": ["\\Planckconst"],
	"℧": ["\\mho", "conductance"],
	"Ⅎ": ["\\Finv"],
	"ℼ": ["\\Bbbpi"],
	"⅁": ["\\Game"],
	"⅂": ["\\sansLturned"],
	"⅃": ["\\sansLmirrored"],
	"⅄": ["\\Yup"],
	"⅊": ["\\PropertyLine"],
	"∀": ["\\forall"],
	"∁": ["\\complement"],
	"∃": ["\\exists", "at least one exists"],
	"∄": ["\\nexists", "negated exists"],
	"∅": ["\\varnothing", "\\emptyset", "circle, slash"],
	"⌀": ["\\diameter"],
	"⦰": ["\\revemptyset"],
	"⦱": ["\\emptysetobar"],
	"⦲": ["\\emptysetocirc"],
	"⦳": ["\\emptysetoarr"],
	"⦴": ["\\emptysetoarrl"],
	"∆": ["\\increment", "laplacian", "delta", "nabla squared"],
	"∎": ["\\QED"],
	"∞": ["\\infty"],
	"⧜": ["\\iinfin"],
	"⧝": ["\\tieinfty"],
	"⧞": ["\\nvinfty"],
	"♾": ["\\acidfree", "permanent paper sign"],
	"∠": ["\\angle"],
	"∟": ["\\rightangle", "90 degree angle"],
	"∡": ["\\measuredangle", "angle-measured"],
	"∢": ["\\sphericalangle", "angle-spherical"],
	"⊾": ["\\measuredrightangle", "right angle-measured"],
	"⟀": ["\\threedangle"],
	"⦛": ["\\measuredangleleft"],
	"⦜": ["\\rightanglesqr"],
	"⦝": ["\\rightanglemdot"],
	"⦞": ["\\angles"],
	"⦟": ["\\angdnr"],
	"⦠": ["\\gtlpar"],
	"⦡": ["\\sphericalangleup"],
	"⦢": ["\\turnangle"],
	"⦣": ["\\revangle"],
	"⦤": ["\\angleubar"],
	"⦥": ["\\revangleubar"],
	"⦦": ["\\wideangledown"],
	"⦧": ["\\wideangleup"],
	"⦨": ["\\measanglerutone"],
	"⦩": ["\\measanglelutonw"],
	"⦪": ["\\measanglerdtose"],
	"⦫": ["\\measangleldtosw"],
	"⦬": ["\\measangleurtone"],
	"⦭": ["\\measangleultonw"],
	"⦮": ["\\measangledrtose"],
	"⦯": ["\\measangledltosw"],
	"∴": ["\\therefore"],
	"∵": ["\\because"],
	"∿": ["\\sinewave"],
	"⏦": ["\\accurrent"],
	"⊤": ["\\top"],
	"⊥": ["\\bot"],
	"⊹": ["\\hermitmatrix"],
	"⋯": ["\\unicodecdots", "three dots, centered"],
	"⌂": ["\\house"],
	"⌒": ["\\profline", "profile of a line"],
	"⌓": ["\\profsurf", "profile of a surface"],
	"⌗": ["\\viewdata"],
	"⌙": ["\\turnednot"],
	"⌲": ["\\conictaper"],
	"⌶": ["\\topbot", "top and bottom"],
	"⍀": ["\\APLnotbackslash"],
	"⍼": ["\\rangledownzigzagarrow"],
	"⎯": ["\\harrowextender", "horizontal line extension for arrows"],
	"⎶": ["\\bbrktbrk", "bottom square bracket over top square bracket"],
	"⎸": ["\\lvboxline"],
	"⎹": ["\\rvboxline"],
	"⏤": ["\\strns"],
	"⏧": ["\\elinters"],
	"␢": ["\\blanksymbol"],
	"␣": ["\\mathvisiblespace"],
	"┆": ["\\bdtriplevdash", "doubly broken vert"],
	"▀": ["\\blockuphalf"],
	"▄": ["\\blocklowhalf"],
	"█": ["\\blockfull", "\\eqarray"],
	"▌": ["\\blocklefthalf"],
	"▐": ["\\blockrighthalf"],
	"░": ["\\blockqtrshaded", "25% shaded block"],
	"▒": ["\\blockhalfshaded", "50% shaded block"],
	"▓": ["\\blockthreeqtrshaded", "75% shaded block"],
	"○": ["\\mdlgwhtcircle", "medium large circle"],
	"⚆": ["\\circledrightdot"],
	"⚈": ["\\blackcircledrightdot"],
	"⚇": ["\\circledtwodots"],
	"⚉": ["\\blackcircledtwodots"],
	"⧂": ["\\cirscir"],
	"⧃": ["\\cirE"],
	"⧬": ["\\circledownarrow"],
	"⧭": ["\\blackcircledownarrow"],
	"⧲": ["\\errbarcircle"],
	"⧳": ["\\errbarblackcircle"],
	"⃝": ["\\enclosecircle"],
	"◍": ["\\circlevertfill"],
	"◎": ["\\bullseye"],
	"●": ["\\mdlgblkcircle"],
	"◐": ["\\circlelefthalfblack", "harvey ball"],
	"◑": ["\\circlerighthalfblack"],
	"◒": ["\\circlebottomhalfblack", "circle, filled bottom half"],
	"◓": ["\\circletophalfblack", "circle, filled top half"],
	"◔": ["\\circleurquadblack"],
	"◕": ["\\blackcircleulquadwhite"],
	"◖": ["\\blacklefthalfcircle"],
	"◗": ["\\blackrighthalfcircle"],
	"◴": ["\\circleulquad"],
	"◵": ["\\circlellquad"],
	"◶": ["\\circlelrquad"],
	"◷": ["\\circleurquad"],
	"◌": ["\\dottedcircle"],
	"◦": ["\\smwhtcircle"],
	"⚬": ["\\mdsmwhtcircle"],
	"⦁": ["\\mdsmblkcircle"],
	"⚪": ["\\mdwhtcircle", "medium white circle"],
	"⚫": ["\\mdblkcircle", "medium black circle"],
	"◯": ["\\lgwhtcircle"],
	"⬤": ["\\lgblkcircle"],
	"◠": ["\\topsemicircle"],
	"◡": ["\\botsemicircle"],
	"◙": ["\\inversewhitecircle"],
	"◚": ["\\invwhiteupperhalfcircle"],
	"◛": ["\\invwhitelowerhalfcircle"],
	"⬭": ["\\whthorzoval"],
	"⬬": ["\\blkhorzoval"],
	"⬯": ["\\whtvertoval"],
	"⬮": ["\\blkvertoval"],
	"△": ["\\bigtriangleup", "big up triangle, open"],
	"▲": ["\\bigblacktriangleup"],
	"⟁": ["\\whiteinwhitetriangle"],
	"⧊": ["\\triangleodot"],
	"⧋": ["\\triangleubar"],
	"⧌": ["\\triangles"],
	"◭": ["\\triangleleftblack"],
	"◮": ["\\trianglerightblack"],
	"▴": ["\\blacktriangle", "up triangle, filled"],
	"⧍": ["\\triangleserifs"],
	"⃤": ["\\enclosetriangle"],
	"▽": ["\\bigtriangledown", "big down triangle, open"],
	"▼": ["\\bigblacktriangledown", "big down triangle, filled"],
	"⧨": ["\\downtriangleleftblack"],
	"⧩": ["\\downtrianglerightblack"],
	"▿": ["\\triangledown", "down triangle, open"],
	"▾": ["\\blacktriangledown", "down triangle, filled"],
	"◁": ["\\triangleleft", "large left triangle, open"],
	"◀": ["\\blacktriangleleft", "large left triangle, filled"],
	"⩤": ["\\dsub"],
	"▷": ["\\triangleright", "large right triangle, open"],
	"▶": ["\\blacktriangleright", "large right triangle, filled"],
	"⩥": ["\\rsub"],
	"⊿": ["\\varlrtriangle"],
	"◿": ["\\lrtriangle"],
	"◢": ["\\lrblacktriangle"],
	"◺": ["\\lltriangle"],
	"◣": ["\\llblacktriangle"],
	"◸": ["\\ultriangle"],
	"◤": ["\\ulblacktriangle"],
	"◹": ["\\urtriangle"],
	"◥": ["\\urblacktriangle"],
	"◻": ["\\mdwhtsquare"],
	"◼": ["\\mdblksquare"],
	"□": ["\\mdlgwhtsquare", "\\box", "square, open"],
	"■": ["\\mdlgblksquare", "\\matrix", "square, filled"],
	"⟤": ["\\whitesquaretickleft"],
	"⟥": ["\\whitesquaretickright"],
	"⧅": ["\\boxbslash"],
	"⧈": ["\\boxbox"],
	"◫": ["\\boxbar", "vertical bar in box"],
	"⃞": ["\\enclosesquare"],
	"▢": ["\\squoval"],
	"▣": ["\\blackinwhitesquare"],
	"▤": ["\\squarehfill", "square, horizontal rule filled"],
	"▥": ["\\squarevfill", "square, vertical rule filled"],
	"▦": ["\\squarehvfill"],
	"▧": ["\\squarenwsefill", "square, nw-to-se rule filled"],
	"▨": ["\\squareneswfill", "square, ne-to-sw rule filled"],
	"▩": ["\\squarecrossfill"],
	"◧": ["\\squareleftblack", "square, filled left half"],
	"◨": ["\\squarerightblack", "square, filled right half"],
	"◩": ["\\squareulblack", "square, filled top left corner"],
	"◪": ["\\squarelrblack", "square, filled bottom right corner"],
	"⬒": ["\\squaretopblack", "square, filled top half"],
	"⬓": ["\\squarebotblack", "square, filled bottom half"],
	"⬔": ["\\squareurblack", "square, filled upper right diagonal"],
	"⬕": ["\\squarellblack", "square, filled lower left diagonal"],
	"◰": ["\\squareulquad"],
	"◱": ["\\squarellquad"],
	"◲": ["\\squarelrquad"],
	"◳": ["\\squareurquad"],
	"⬚": ["\\dottedsquare"],
	"⬞": ["\\vysmwhtsquare"],
	"⬝": ["\\vysmblksquare"],
	"▫": ["\\smwhtsquare"],
	"▪": ["\\smblksquare", "\\blacksquare", "sq bullet, filled"],
	"◽": ["\\mdsmwhtsquare"],
	"◾": ["\\mdsmblksquare"],
	"⬜": ["\\lgwhtsquare"],
	"⬛": ["\\lgblksquare"],
	"▯": ["\\vrectangle"],
	"▮": ["\\vrectangleblack"],
	"▭": ["\\hrectangle", "\\rect", "horizontal rectangle, open"],
	"▬": ["\\hrectangleblack", "horizontal rectangle, filled"],
	"▱": ["\\parallelogram", "parallelogram, open"],
	"▰": ["\\parallelogramblack", "parallelogram, filled"],
	"⏢": ["\\trapezium", "trapezium, open"],
	"⏥": ["\\fltns"],
	"⍓": ["\\APLboxupcaret", "boxed up caret"],
	"⍰": ["\\APLboxquestion", "boxed question mark"],
	"⟐": ["\\diamondcdot"],
	"⟠": ["\\lozengeminus"],
	"⟡": ["\\concavediamond", "\\phantom"],
	"⟢": ["\\concavediamondtickleft"],
	"⟣": ["\\concavediamondtickright"],
	"⧪": ["\\blackdiamonddownarrow"],
	"⧰": ["\\errbardiamond"],
	"⧱": ["\\errbarblackdiamond"],
	"⌑": ["\\sqlozenge"],
	"⋄": ["\\smwhtdiamond"],
	"⬩": ["\\smblkdiamond"],
	"⬫": ["\\smwhtlozenge"],
	"⬪": ["\\smblklozenge"],
	"⬦": ["\\mdwhtdiamond"],
	"⬥": ["\\mdblkdiamond"],
	"◇": ["\\mdlgwhtdiamond", "diamond, open"],
	"◆": ["\\mdlgblkdiamond", "diamond, filled"],
	"⬨": ["\\mdwhtlozenge"],
	"⬧": ["\\mdblklozenge"],
	"◈": ["\\blackinwhitediamond"],
	"⬖": ["\\diamondleftblack"],
	"⬗": ["\\diamondrightblack"],
	"⬘": ["\\diamondtopblack"],
	"⬙": ["\\diamondbotblack"],
	"⃟": ["\\enclosediamond"],
	"◊": ["\\mdlgwhtlozenge", "total mark"],
	"⧫": ["\\mdlgblklozenge"],
	"⬠": ["\\pentagon"],
	"⬟": ["\\pentagonblack"],
	"⭔": ["\\rightpentagon"],
	"⭓": ["\\rightpentagonblack"],
	"⎔": ["\\hexagon", "horizontal benzene ring", "hexagon flat open"],
	"⬣": ["\\hexagonblack"],
	"⬡": ["\\varhexagon"],
	"⬢": ["\\varhexagonblack"],
	"⌬": ["\\varhexagonlrbonds", "six carbon ring, corner down, double bonds lower right etc"],
	"⏣": ["\\benzenr"],
	"⋖": ["\\lessdot"],
	"⋗": ["\\gtrdot"],
	"⩹": ["\\ltcir"],
	"⩺": ["\\gtcir"],
	"⩻": ["\\ltquest"],
	"⩼": ["\\gtquest"],
	"⪇": ["\\lneq"],
	"⪈": ["\\gneq"],
	"≦": ["\\leqq"],
	"≨": ["\\lneqq"],
	"≧": ["\\geqq"],
	"≩": ["\\gneqq"],
	"⋜": ["\\eqless"],
	"⋝": ["\\eqgtr"],
	"⪙": ["\\eqqless"],
	"⪚": ["\\eqqgtr"],
	"⩽": ["\\leqslant"],
	"⩾": ["\\geqslant"],
	"⩿": ["\\lesdot"],
	"⪀": ["\\gesdot"],
	"⪁": ["\\lesdoto"],
	"⪂": ["\\gesdoto"],
	"⪃": ["\\lesdotor"],
	"⪄": ["\\gesdotol"],
	"⪕": ["\\eqslantless"],
	"⪖": ["\\eqslantgtr"],
	"⪗": ["\\elsdot"],
	"⪘": ["\\egsdot"],
	"⫹": ["\\leqqslant"],
	"⫺": ["\\geqqslant"],
	"⪛": ["\\eqqslantless"],
	"⪜": ["\\eqqslantgtr"],
	"≲": ["\\lesssim", "less, similar"],
	"≴": ["\\nlesssim", "not less, similar"],
	"≳": ["\\gtrsim", "greater, similar"],
	"≵": ["\\ngtrsim", "not greater, similar"],
	"⋦": ["\\lnsim", "less, not similar"],
	"⋧": ["\\gnsim", "greater, not similar"],
	"⪅": ["\\lessapprox"],
	"⪉": ["\\lnapprox"],
	"⪆": ["\\gtrapprox"],
	"⪊": ["\\gnapprox"],
	"⪍": ["\\lsime"],
	"⪎": ["\\gsime"],
	"⪝": ["\\simless"],
	"⪞": ["\\simgtr"],
	"⪟": ["\\simlE"],
	"⪠": ["\\simgE"],
	"⪣": ["\\partialmeetcontraction"],
	"⋘": ["\\lll", "\\llless", "triple less-than"],
	"⫷": ["\\lllnest", "stacked very much less-than"],
	"⋙": ["\\ggg", "\\gggtr", "triple greater-than"],
	"⫸": ["\\gggnest", "stacked very much greater-than"],
	"≷": ["\\gtrless"],
	"≹": ["\\ngtrless"],
	"⋚": ["\\lesseqgtr"],
	"⋛": ["\\gtreqless"],
	"⪋": ["\\lesseqqgtr"],
	"⪌": ["\\gtreqqless"],
	"⪏": ["\\lsimg"],
	"⪐": ["\\gsiml"],
	"⪑": ["\\lgE"],
	"⪒": ["\\glE"],
	"⪓": ["\\lesges"],
	"⪔": ["\\gesles"],
	"⪤": ["\\glj"],
	"⪥": ["\\gla"],
	"⪪": ["\\smt"],
	"⪫": ["\\lat"],
	"⪬": ["\\smte"],
	"⪭": ["\\late"],
	"⋞": ["\\curlyeqprec", "curly equals, precedes"],
	"⋟": ["\\curlyeqsucc", "curly equals, succeeds"],
	"⪯": ["\\preceq"],
	"⪱": ["\\precneq"],
	"⪰": ["\\succeq"],
	"⪲": ["\\succneq"],
	"⪳": ["\\preceqq"],
	"⪵": ["\\precneqq"],
	"⪴": ["\\succeqq"],
	"⪶": ["\\succneqq"],
	"≾": ["\\precsim", "precedes, similar"],
	"⋨": ["\\precnsim", "precedes, not similar"],
	"≿": ["\\succsim", "succeeds, similar"],
	"⋩": ["\\succnsim", "succeeds, not similar"],
	"⪷": ["\\precapprox"],
	"⪹": ["\\precnapprox"],
	"⪸": ["\\succapprox"],
	"⪺": ["\\succnapprox"],
	"⪻": ["\\Prec"],
	"⪼": ["\\Succ"],
	"⊰": ["\\prurel"],
	"⊱": ["\\scurel"],
	"⥽": ["\\rightfishtail"],
	"⥼": ["\\leftfishtail"],
	"∊": ["\\smallin", "small set membership"],
	"∍": ["\\smallni", "\\ni", "\\owns"],
	"⋲": ["\\disin"],
	"⋺": ["\\nisd"],
	"⋳": ["\\varisins"],
	"⋻": ["\\varnis"],
	"⋴": ["\\isins"],
	"⋼": ["\\nis"],
	"⋵": ["\\isindot"],
	"⋶": ["\\varisinobar"],
	"⋽": ["\\varniobar"],
	"⋷": ["\\isinobar"],
	"⋾": ["\\niobar"],
	"⋸": ["\\isinvb"],
	"⋹": ["\\isinE"],
	"⟒": ["\\upin"],
	"⫙": ["\\forkv"],
	"⋔": ["\\pitchfork"],
	"⫚": ["\\topfork"],
	"⫛": ["\\mlcp"],
	"⫝̸": ["\\forks"],
	"⫝": ["\\forksnot"],
	"⋿": ["\\bagmember"],
	"⪽": ["\\subsetdot"],
	"⪾": ["\\supsetdot"],
	"⪿": ["\\subsetplus"],
	"⫀": ["\\supsetplus"],
	"⫁": ["\\submult"],
	"⫂": ["\\supmult"],
	"⟈": ["\\bsolhsub"],
	"⟉": ["\\suphsol"],
	"⟃": ["\\subsetcirc"],
	"⟄": ["\\supsetcirc"],
	"⋐": ["\\Subset"],
	"⋑": ["\\Supset"],
	"⫏": ["\\csub"],
	"⫐": ["\\csup"],
	"⊊": ["\\subsetneq"],
	"⊋": ["\\supsetneq"],
	"⫃": ["\\subedot"],
	"⫄": ["\\supedot"],
	"⫑": ["\\csube"],
	"⫒": ["\\csupe"],
	"⫅": ["\\subseteqq"],
	"⫆": ["\\supseteqq"],
	"⫇": ["\\subsim"],
	"⫈": ["\\supsim"],
	"⫉": ["\\subsetapprox"],
	"⫊": ["\\supsetapprox"],
	"⫋": ["\\subsetneqq"],
	"⫌": ["\\supsetneqq"],
	"⫓": ["\\subsup"],
	"⫔": ["\\supsub"],
	"⫕": ["\\subsub"],
	"⫖": ["\\supsup"],
	"⫗": ["\\suphsub"],
	"⫘": ["\\supdsub"],
	"⊏": ["\\sqsubset", "square subset"],
	"⊐": ["\\sqsupset", "square superset"],
	"⫍": ["\\lsqhook"],
	"⫎": ["\\rsqhook"],
	"⊑": ["\\sqsubseteq", "square subset, equals"],
	"⋢": ["\\nsqsubseteq", "not, square subset, equals"],
	"⊒": ["\\sqsupseteq", "square superset, equals"],
	"⋣": ["\\nsqsupseteq", "not, square superset, equals"],
	"⋤": ["\\sqsubsetneq", "square subset, not equals"],
	"⋥": ["\\sqsupsetneq", "square superset, not equals"],
	"⩵": ["\\eqeq"],
	"⩶": ["\\eqeqeq"],
	"⧦": ["\\gleichstark"],
	"≖": ["\\eqcirc", "circle on equals sign"],
	"≝": ["\\eqdef"],
	"≟": ["\\questeq", "equal with question mark"],
	"≗": ["\\circeq", "circle, equals"],
	"≘": ["\\arceq", "arc, equals"],
	"≙": ["\\wedgeq", "wedge, equals"],
	"≚": ["\\veeeq", "logical or, equals"],
	"≛": ["\\stareq"],
	"⩮": ["\\asteq"],
	"≜": ["\\triangleq", "triangle, equals"],
	"≞": ["\\measeq"],
	"⪮": ["\\bumpeqq"],
	"⩦": ["\\eqdot"],
	"⩧": ["\\dotequiv"],
	"⋕": ["\\equalparallel"],
	"⩨": ["\\equivVert"],
	"⩩": ["\\equivVvert"],
	"⧣": ["\\eparsl"],
	"⧤": ["\\smeparsl"],
	"⧥": ["\\eqvparsl"],
	"≍": ["\\asymp", "asymptotically equal to"],
	"≭": ["\\nasymp", "not asymptotically equal to"],
	"≎": ["\\Bumpeq", "bumpy equals"],
	"≏": ["\\bumpeq", "bumpy equals, equals"],
	"≐": ["\\doteq", "equals, single dot above"],
	"≑": ["\\Doteq", "\\doteqdot", "equals, even dots"],
	"≒": ["\\fallingdotseq", "equals, falling dots"],
	"≓": ["\\risingdotseq", "equals, rising dots"],
	"≔": ["\\coloneq"],
	"⩴": ["\\Coloneq"],
	"≕": ["\\eqcolon"],
	"⩷": ["\\ddotseq"],
	"≣": ["\\Equiv", "four lines"],
	"⩸": ["\\equivDD"],
	"⋍": ["\\backsimeq", "reverse similar, equals"],
	"≅": ["\\cong(l)", "congruent with"],
	"≆": ["\\simneqq", "similar, not equals"],
	"≇": ["\\ncong", "not congruent with"],
	"≌": ["\\backcong"],
	"≂": ["\\eqsim", "equals, similar"],
	"≊": ["\\approxeq", "approximate, equals"],
	"≋": ["\\approxident", "approximately identical to"],
	"⩬": ["\\simminussim"],
	"⩭": ["\\congdot"],
	"⩯": ["\\hatapprox"],
	"⩰": ["\\approxeqq"],
	"⩳": ["\\eqqsim"],
	"∻": ["\\kernelcontraction"],
	"⩪": ["\\dotsim"],
	"⩫": ["\\simrdots"],
	"∽": ["\\backsim", "reverse similar"],
	"⊲": ["\\vartriangleleft", "left triangle, open, variant"],
	"⋪": ["\\nvartriangleleft", "not left triangle"],
	"⊳": ["\\vartriangleright", "right triangle, open, variant"],
	"⋫": ["\\nvartriangleright", "not right triangle"],
	"⊴": ["\\trianglelefteq", "left triangle, equals"],
	"⋬": ["\\ntrianglelefteq", "not left triangle, equals"],
	"⊵": ["\\trianglerighteq", "right triangle, equals"],
	"⋭": ["\\ntrianglerighteq", "not right triangle, equals"],
	"⧡": ["\\lrtriangleeq"],
	"⧏": ["\\ltrivb"],
	"⧐": ["\\vbrtri"],
	"⪦": ["\\ltcc"],
	"⪧": ["\\gtcc"],
	"⪨": ["\\lescc"],
	"⪩": ["\\gescc"],
	"⧎": ["\\rtriltri"],
	"⊢": ["\\vdash", "vertical, dash"],
	"⊬": ["\\nvdash", "not vertical, dash"],
	"⊣": ["\\dashv", "dash, vertical"],
	"⊦": ["\\assert", "vertical, short dash"],
	"⫞": ["\\shortlefttack"],
	"⫟": ["\\shortdowntack"],
	"⫠": ["\\shortuptack"],
	"⟝": ["\\vlongdash"],
	"⟞": ["\\longdashv"],
	"⊧": ["\\models", "vertical, short double dash"],
	"⊨": ["\\vDash", "vertical, double dash"],
	"⊭": ["\\nvDash", "not vertical, double dash"],
	"⊩": ["\\Vdash", "double vertical, dash"],
	"⊮": ["\\nVdash", "not double vertical, dash"],
	"⊪": ["\\Vvdash", "triple vertical, dash"],
	"⊫": ["\\VDash", "double vert, double dash"],
	"⊯": ["\\nVDash", "not double vert, double dash"],
	"⟚": ["\\DashVDash", "left and right double dash"],
	"⟛": ["\\dashVdash", "left and right tack"],
	"⫢": ["\\vDdash"],
	"⫣": ["\\dashV"],
	"⫤": ["\\Dashv"],
	"⫥": ["\\DashV"],
	"⫦": ["\\varVdash"],
	"⫧": ["\\Barv"],
	"⫨": ["\\vBar"],
	"⫩": ["\\vBarv"],
	"⫪": ["\\barV"],
	"⫫": ["\\Vbar"],
	"⫬": ["\\Not"],
	"⫭": ["\\bNot"],
	"≶": ["\\lessgtr", "less, greater"],
	"≸": ["\\nlessgtr", "not less, greater"],
	"<": ["\\less"],
	"≮": ["\\nless"],
	">": ["\\greater"],
	"≯": ["\\ngtr"],
	"≪": ["\\ll"],
	"⪡": ["\\Lt"],
	"≫": ["\\gg"],
	"⪢": ["\\Gt"],
	"≤": ["\\leq", "\\le"],
	"≰": ["\\nleq", "not less-than-or-equal"],
	"≥": ["\\geq", "\\ge"],
	"≱": ["\\ngeq", "not greater-than-or-equal"],
	"≺": ["\\prec"],
	"⊀": ["\\nprec"],
	"≻": ["\\succ"],
	"⊁": ["\\nsucc"],
	"≼": ["\\preccurlyeq", "precedes, curly equals"],
	"⋠": ["\\npreccurlyeq", "not precedes, curly equals"],
	"≽": ["\\succcurlyeq", "succeeds, curly equals"],
	"⋡": ["\\nsucccurlyeq", "not succeeds, curly equals"],
	"∈": ["\\in", "set membership", "variant"],
	"∉": ["\\notin(l)", "negated set membership"],
	"∋": ["\\ni", "contains", "variant"],
	"∌": ["\\nni", "negated contains", "variant"],
	"∝": ["\\propto", "is proportional to"],
	"=": ["\\equal"],
	"≠": ["\\ne", "\\neq"],
	"≡": ["\\equiv"],
	"≢": ["\\nequiv"],
	"∼": ["\\sim", "similar"],
	"≁": ["\\nsim", "not similar"],
	"≃": ["\\simeq sime", "similar, equals"],
	"≄": ["\\nsime", "\\nsimeq", "not similar, equals"],
	"≈": ["\\approx", "approximate"],
	"≉": ["\\napprox", "not approximate"],
	"⊂": ["\\subset", "is implied by"],
	"⊄": ["\\nsubset"],
	"⊃": ["\\supset", "implies"],
	"⊅": ["\\nsupset"],
	"⊆": ["\\subseteq"],
	"⊈": ["\\nsubseteq", "not subset, equals"],
	"⊇": ["\\supseteq"],
	"⊉": ["\\nsupseteq", "not superset, equals"],
	"⋈": ["\\bowtie"],
	"⧓": ["\\fbowtie"],
	"⧔": ["\\lftimes"],
	"⧑": ["\\lfbowtie"],
	"⧒": ["\\rfbowtie"],
	"⧕": ["\\rftimes"],
	"⋮": ["\\vdots"],
	"⋰": ["\\adots", "three dots, ascending"],
	"⋱": ["\\ddots", "three dots, descending"],
	"≬": ["\\between"],
	"⁐": ["\\closure"],
	"⌢": ["\\frown", "down curve"],
	"⌣": ["\\smile", "up curve"],
	"⌿": ["\\APLnotslash", "solidus, bar through"],
	"▵": ["\\vartriangle", "\\triangle", "up triangle, open"],
	"⟂": ["\\perp"],
	"⫡": ["\\perps"],
	"⟓": ["\\pullback"],
	"⟔": ["\\pushout"],
	"⧟": ["\\dualmap"],
	"⊶": ["\\origof"],
	"⊷": ["\\imageof"],
	"⊸": ["\\multimap"],
	"⫯": ["\\cirmid"],
	"⫰": ["\\midcir"],
	"⟜": ["\\multimapinv"],
	"⟟": ["\\cirbot"],
	"⥾": ["\\upfishtail"],
	"⥿": ["\\downfishtail"],
	"⦂": ["\\typecolon"],
	"∶": ["\\mathratio"],
	"∷": ["\\Colon", "two colons"],
	"∹": ["\\dashcolon", "-:"],
	"∺": ["\\dotsminusdots", "minus with four dots"],
	"⧴": ["\\ruledelayed"],
	"⩙": ["\\veeonwedge"],
	"∣": ["\\mid"],
	"∤": ["\\nmid", "negated mid"],
	"∥": ["\\parallel"],
	"∦": ["\\nparallel"],
	"⫮": ["\\revnmid"],
	"⫲": ["\\nhpar"],
	"⫳": ["\\parsim"],
	"¯": ["\\overbar"],
	"▁": ["\\underbar"],
	"⬄": ["\\hphantom"],
	"⇳": ["\\vphantom"],
	"⬍": ["\\smash"],
	"⬆": ["\\asmash"],
	"⬇": ["\\dsmash"],
	"⬌": ["\\hsmash"],
	"♠": ["\\spadesuit"],
	"♤": ["\\varspadesuit"],
	"♡": ["\\heartsuit"],
	"♥": ["\\varheartsuit"],
	"♢": ["\\diamondsuit"],
	"♦": ["\\vardiamondsuit"],
	"♣": ["\\clubsuit"],
	"♧": ["\\varclubsuit"],
	"⚀": ["\\dicei"],
	"⚁": ["\\diceii"],
	"⚂": ["\\diceiii"],
	"⚃": ["\\diceiv"],
	"⚄": ["\\dicev"],
	"⚅": ["\\dicevi"],
	"♩": ["\\quarternote", "music note", "sung text sign"],
	"♪": ["\\eighthnote"],
	"♫": ["\\twonotes"],
	"♭": ["\\flat"],
	"♮": ["\\natural"],
	"♯": ["\\sharp"],
	"♀": ["\\female"],
	"♂": ["\\male"],
	"⚥": ["\\Hermaphrodite"],
	"⚲": ["\\neuter"],
	"◉": ["\\fisheye"],
	"◘": ["\\inversebullet"],
	"◜": ["\\ularc"],
	"◝": ["\\urarc"],
	"◞": ["\\lrarc"],
	"◟": ["\\llarc"],
	"★": ["\\bigstar", "star, filled"],
	"☆": ["\\bigwhitestar", "star, open"],
	"☉": ["\\astrosun"],
	"☡": ["\\danger", "dangerous bend"],
	"☻": ["\\blacksmiley"],
	"☼": ["\\sun"],
	"☽": ["\\rightmoon"],
	"☾": ["\\leftmoon"],
	"✓": ["\\checkmark", "tick"],
	"✠": ["\\maltese"],
	"✪": ["\\circledstar"],
	"✶": ["\\varstar"],
	"✽": ["\\dingasterisk"],
	"➛": ["\\draftingarrow", "right arrow with bold head"],
	"⤫": ["\\rdiagovfdiag"],
	"⤬": ["\\fdiagovrdiag"],
	"⦙": ["\\fourvdots"],
	"⦚": ["\\vzigzag"],
	"⦺": ["\\obot"],
	"⧉": ["\\boxonbox"],
	"⧠": ["\\laplac"],
	"⧧": ["\\thermod"],
	"⧮": ["\\errbarsquare"],
	"⧯": ["\\errbarblacksquare"],
	"⫱": ["\\topcir"],
	"⭐": ["\\medwhitestar", "white medium star"],
	"⭑": ["\\medblackstar", "black medium star"],
	"⭒": ["\\smwhitestar"],
	"〒": ["\\postalmark"],
	"〰": ["\\hzigzag", "zigzag"],
	"⎛": ["\\lparenuend"],
	"⎜": ["\\lparenextender"],
	"⎝": ["\\lparenlend"],
	"⎡": ["\\lbrackuend"],
	"⎢": ["\\lbrackextender"],
	"⎣": ["\\lbracklend"],
	"⎧": ["\\lbraceuend"],
	"⎨": ["\\lbracemid"],
	"⎪": ["\\vbraceextender"],
	"⎩": ["\\lbracelend"],
	"⎞": ["\\rparenuend"],
	"⎟": ["\\rparenextender"],
	"⎠": ["\\rparenlend"],
	"⎤": ["\\rbrackuend"],
	"⎥": ["\\rbrackextender"],
	"⎦": ["\\rbracklend"],
	"⎫": ["\\rbraceuend"],
	"⎬": ["\\rbracemid"],
	"⎭": ["\\rbracelend"],
	"⎲": ["\\sumtop"],
	"⎳": ["\\sumbottom"],
	"⌠": ["\\inttop"],
	"⎮": ["\\intextender"],
	"⌡": ["\\intbottom"],
	"⎷": ["\\sqrtbottom"],
};
